### ISSUE TITLE
ROADMAP v3

### ISSUE THREAD

**Issue by LWJerri** [LWJerri/Pauperial#79]
BACKEND:
- [ ] Setup Nest.js server.
- [ ] Add `/stats/` API endpoint.
- [ ] Add `/contact/` API endpoint.
- [ ] Add `/link/` API endpoint.
- [ ] Add auth API endpoints.

FRONTEND:
- [ ] Setup Vite server.
- [ ] Finish new layout.
- [ ] Finish other things.

New website design:
- https://www.figma.com/file/nyRujWPZK5MB3WXaBHNGld/Pauperial

Project structure:
![image](https://user-images.githubusercontent.com/50290430/190339441-9cc2160e-de89-4a36-9b9b-ed38eb0ace09.png)
